### ISSUE TITLE
Wrong type argument: commandp

### ISSUE THREAD

**Issue by d1egoaz** [jypma/kubectl#1]
Hey, thanks for this package, it looks it'd be a great fit for my workflow, however it is not working for me right now, not sure what's wrong :/

setup:
```
(setq kubectl--kubectl "/usr/local/bin/kubectl")
```

1. `kubectl-choose-context` works
2. `kubectl--namespace-names` works:
<img src="https://screenshot.click/2020-01-21_08-51-41_aclia.png" width="50%" />
3. When I choose a namespace I got this error:

```
/usr/local/bin/kubectl  --context xxxcontext get namespaces --no-headers=true | awk '{print $1}'
kubectl-choose-namespace: Wrong type argument: commandp, (keymap (81 . +format:region) (122 keymap (122 . +multiple-cursors/evil-mc-make-cursor-here) (117 . evil-mc-undo-last-added-cursor) (116 . +multiple-cursors/evil-mc-toggle-cursors) (113 . evil-mc-undo-all-cursors) (80 . evil-mc-make-and-goto-first-cursor) (112 . evil-mc-make-and-goto-prev-cursor) (78 . evil-mc-make-and-goto-last-cursor) (110 . evil-mc-make-and-goto-next-cursor) ...) (82 . +eval/buffer) (114 . +eval:region) (68 . +lookup/references) (100 . +lookup/definition) (45 . evil-numbers/dec-at-pt) (61 . evil-numbers/inc-at-pt) (121 . +evil:yank-unindented) ...)
```

**Comment by jypma** [comment]
Thanks for reporting!

`kubectl-choose-namespace` ends by trying to invoke `g` on the current buffer (see [here](https://github.com/jypma/kubectl/blob/master/kubectl.el#L103)):
```
  (call-interactively (cdr (car (minor-mode-key-binding "g")))))
```

If it's invokes from `kubectl-deployments`, that should then load the deployments in that namespace. Is `kubectl-deployments` indeed what you started from?

**Comment by d1egoaz** [comment]
still failing for me.

I changed `kubectl-choose-namespace` to:
``` elisp
(defun kubectl-choose-namespace (namespace)
  "Select a new namespace interactively"
  (interactive (list (completing-read "Namespace: " (kubectl--namespace-names) nil t)))
  (setq kubectl--namespace namespace)
  (kubectl-pods-refresh))
```

and now I can see the pods list

**Comment by jypma** [comment]
Nice find, thanks! Perhaps it's some incompatibility with `evil`?

The reason I wasn't "just" calling `kubectl-pods-refresh`, is that I wanted to be able to switch namespaces with the same function also in other views, e.g. when viewing a deployment. Do you think there'd be a better way to achieve that, than trying to simulate a press of `g`?

**Comment by d1egoaz** [comment]
> Perhaps it's some incompatibility with evil?

looks like it!

> Do you think there'd be a better way to achieve that, than trying to simulate a press of g?

let me have some time during the next days to read the code, don't expect too much from me, I'm not too familiar with elisp.
